In [3]:
import pandas as pd 
import numpy as np

In [4]:
df = pd.read_csv("D:\\João Carlos Moura\\brasileirao-data-analysis\\data\\raw\\brasileirao.csv")

df.head()

,ano_campeonato,data,rodada,estadio,arbitro,publico,publico_max,time_mandante,time_visitante,tecnico_mandante,...,chutes_bola_parada_mandante,chutes_bola_parada_visitante,defesas_mandante,defesas_visitante,impedimentos_mandante,impedimentos_visitante,chutes_mandante,chutes_visitante,chutes_fora_mandante,chutes_fora_visitante
0,2005,2005-10-08,31,Estádio Durival Britto e Silva,NaN,NaN,NaN,Paraná,Fluminense,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2005,2005-04-23,1,Estádio Durival Britto e Silva,NaN,NaN,NaN,Paraná,Goiás EC,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2005,2005-08-21,21,Estádio Durival Britto e Silva,NaN,NaN,NaN,Paraná,Vasco da Gama,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2005,2005-08-28,23,Estádio Durival Britto e Silva,NaN,NaN,NaN,Paraná,São Paulo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2005,2005-06-26,9,Estádio Olímpico Nilton Santos,NaN,NaN,NaN,Botafogo,Figueirense FC,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.shape

(8453, 35)

In [6]:
df.columns

Index(['ano_campeonato', 'data', 'rodada', 'estadio', 'arbitro', 'publico',
       'publico_max', 'time_mandante', 'time_visitante', 'tecnico_mandante',
       'tecnico_visitante', 'colocacao_mandante', 'colocacao_visitante',
       'valor_equipe_titular_mandante', 'valor_equipe_titular_visitante',
       'idade_media_titular_mandante', 'idade_media_titular_visitante',
       'gols_mandante', 'gols_visitante', 'gols_1_tempo_mandante',
       'gols_1_tempo_visitante', 'escanteios_mandante', 'escanteios_visitante',
       'faltas_mandante', 'faltas_visitante', 'chutes_bola_parada_mandante',
       'chutes_bola_parada_visitante', 'defesas_mandante', 'defesas_visitante',
       'impedimentos_mandante', 'impedimentos_visitante', 'chutes_mandante',
       'chutes_visitante', 'chutes_fora_mandante', 'chutes_fora_visitante'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8453 entries, 0 to 8452
Data columns (total 35 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ano_campeonato                  8453 non-null   int64
 1   data                            8453 non-null   str
 2   rodada                          8453 non-null   int64
 3   estadio                         8442 non-null   str
 4   arbitro                         6743 non-null   str
 5   publico                         6742 non-null   float64
 6   publico_max                     4181 non-null   float64
 7   time_mandante                   8453 non-null   str
 8   time_visitante                  8453 non-null   str
 9   tecnico_mandante                6299 non-null   str
 10  tecnico_visitante               6299 non-null   str
 11  colocacao_mandante              6743 non-null   float64
 12  colocacao_visitante             6743 non-null   float64
 13  valor_equipe_titular_mandante   6355 non-null   float64
 14  valor_equipe_titular_visitante  6355 non-null   float64
 15  idade_media_titular_mandante    6353 non-null   float64
 16  idade_media_titular_visitante   6353 non-null   float64
 17  gols_mandante                   8452 non-null   float64
 18  gols_visitante                  8452 non-null   float64
 19  gols_1_tempo_mandante           6732 non-null   float64
 20  gols_1_tempo_visitante          6732 non-null   float64
 21  escanteios_mandante             2087 non-null   float64
 22  escanteios_visitante            2087 non-null   float64
 23  faltas_mandante                 2087 non-null   float64
 24  faltas_visitante                2087 non-null   float64
 25  chutes_bola_parada_mandante     2087 non-null   float64
 26  chutes_bola_parada_visitante    2087 non-null   float64
 27  defesas_mandante                2087 non-null   float64
 28  defesas_visitante               2087 non-null   float64
 29  impedimentos_mandante           2087 non-null   float64
 30  impedimentos_visitante          2087 non-null   float64
 31  chutes_mandante                 2087 non-null   float64
 32  chutes_visitante                2087 non-null   float64
 33  chutes_fora_mandante            2087 non-null   float64
 34  chutes_fora_visitante           2087 non-null   float64
dtypes: float64(26), int64(2), str(7)
memory usage: 2.3 MB

In [8]:
df.describe

<bound method NDFrame.describe of       ano_campeonato        data  rodada  \
0               2005  2005-10-08      31
1               2005  2005-04-23       1
2               2005  2005-08-21      21
3               2005  2005-08-28      23
4               2005  2005-06-26       9
...              ...         ...     ...
8448            2017  2017-10-15      28
8449            2017  2017-10-22      30
8450            2017  2017-10-28      31
8451            2017  2017-11-09      33
8452            2017  2017-11-19      36

                                          estadio                   arbitro  \
0                  Estádio Durival Britto e Silva                       NaN
1                  Estádio Durival Britto e Silva                       NaN
2                  Estádio Durival Britto e Silva                       NaN
3                  Estádio Durival Britto e Silva                       NaN
4                  Estádio Olímpico Nilton Santos                       NaN
...                                           ...                       ...
8448  Estádio Municipal Paulo Machado de Carvalho  Marcelo de Lima Henrique
8449  Estádio Municipal Paulo Machado de Carvalho              Rafael Traci
8450  Estádio Municipal Paulo Machado de Carvalho          Anderson Daronco
8451  Estádio Municipal Paulo Machado de Carvalho  Marcelo de Lima Henrique
8452  Estádio Municipal Paulo Machado de Carvalho            Wilton Sampaio

      publico  publico_max time_mandante  time_visitante tecnico_mandante  \
0         NaN          NaN        Paraná      Fluminense              NaN
1         NaN          NaN        Paraná        Goiás EC              NaN
2         NaN          NaN        Paraná   Vasco da Gama              NaN
3         NaN          NaN        Paraná       São Paulo              NaN
4         NaN          NaN      Botafogo  Figueirense FC              NaN
...       ...          ...           ...             ...              ...
8448  26833.0      37730.0     São Paulo     Atlético-PR   Dorival Júnior
8449  32965.0      37730.0     São Paulo        Flamengo   Dorival Júnior
8450  40004.0      40500.0     São Paulo       Santos FC   Dorival Júnior
8451  35037.0      37730.0     São Paulo     Chapecoense   Dorival Júnior
8452  25771.0      37730.0     São Paulo        Botafogo   Dorival Júnior

      ... chutes_bola_parada_mandante  chutes_bola_parada_visitante  \
0     ...                         NaN                           NaN
1     ...                         NaN                           NaN
2     ...                         NaN                           NaN
3     ...                         NaN                           NaN
4     ...                         NaN                           NaN
...   ...                         ...                           ...
8448  ...                         NaN                           NaN
8449  ...                         NaN                           NaN
8450  ...                         NaN                           NaN
8451  ...                         NaN                           NaN
8452  ...                         NaN                           NaN

      defesas_mandante  defesas_visitante  impedimentos_mandante  \
0                  NaN                NaN                    NaN
1                  NaN                NaN                    NaN
2                  NaN                NaN                    NaN
3                  NaN                NaN                    NaN
4                  NaN                NaN                    NaN
...                ...                ...                    ...
8448               NaN                NaN                    NaN
8449               NaN                NaN                    NaN
8450               NaN                NaN                    NaN
8451               NaN                NaN                    NaN
8452               NaN                NaN                    NaN

      impedimentos_visitante  chutes_mandante  chutes_visitante  \
0                        NaN              NaN               NaN
1                        NaN              NaN               NaN
2                        NaN              NaN               NaN
3                        NaN              NaN               NaN
4                        NaN              NaN               NaN
...                      ...              ...               ...
8448                     NaN              NaN               NaN
8449                     NaN              NaN               NaN
8450                     NaN              NaN               NaN
8451                     NaN              NaN               NaN
8452                     NaN              NaN               NaN

      chutes_fora_mandante  chutes_fora_visitante
0                      NaN                    NaN
1                      NaN                    NaN
2                      NaN                    NaN
3                      NaN                    NaN
4                      NaN                    NaN
...                    ...                    ...
8448                   NaN                    NaN
8449                   NaN                    NaN
8450                   NaN                    NaN
8451                   NaN                    NaN
8452                   NaN                    NaN

[8453 rows x 35 columns]>

In [9]:
df.isnull().sum()

ano_campeonato                       0
data                                 0
rodada                               0
estadio                             11
arbitro                           1710
publico                           1711
publico_max                       4272
time_mandante                        0
time_visitante                       0
tecnico_mandante                  2154
tecnico_visitante                 2154
colocacao_mandante                1710
colocacao_visitante               1710
valor_equipe_titular_mandante     2098
valor_equipe_titular_visitante    2098
idade_media_titular_mandante      2100
idade_media_titular_visitante     2100
gols_mandante                        1
gols_visitante                       1
gols_1_tempo_mandante             1721
gols_1_tempo_visitante            1721
escanteios_mandante               6366
escanteios_visitante              6366
faltas_mandante                   6366
faltas_visitante                  6366
chutes_bola_parada_mandante       6366
chutes_bola_parada_visitante      6366
defesas_mandante                  6366
defesas_visitante                 6366
impedimentos_mandante             6366
impedimentos_visitante            6366
chutes_mandante                   6366
chutes_visitante                  6366
chutes_fora_mandante              6366
chutes_fora_visitante             6366
dtype: int64

In [10]:
df['ano_campeonato']

0       2005
1       2005
2       2005
3       2005
4       2005
        ...
8448    2017
8449    2017
8450    2017
8451    2017
8452    2017
Name: ano_campeonato, Length: 8453, dtype: int64

In [11]:
df['arbitro']

0                            NaN
1                            NaN
2                            NaN
3                            NaN
4                            NaN
                  ...
8448    Marcelo de Lima Henrique
8449                Rafael Traci
8450            Anderson Daronco
8451    Marcelo de Lima Henrique
8452              Wilton Sampaio
Name: arbitro, Length: 8453, dtype: str

In [12]:
df[['ano_campeonato', 'arbitro']]

      ano_campeonato                   arbitro
0               2005                       NaN
1               2005                       NaN
2               2005                       NaN
3               2005                       NaN
4               2005                       NaN
...              ...                       ...
8448            2017  Marcelo de Lima Henrique
8449            2017              Rafael Traci
8450            2017          Anderson Daronco
8451            2017  Marcelo de Lima Henrique
8452            2017            Wilton Sampaio

[8453 rows x 2 columns]

## Observações iniciais

- A base contém **8453 partidas** e **35 colunas**.
- Os dados abrangem diversas temporadas do Campeonato Brasileiro.
- Algumas colunas apresentam valores ausentes, principalmente **arbitro**, indicando informações não registradas em determinadas partidas.
- Não foram encontradas linhas duplicadas.
- A coluna **data** foi convertida para o formato datetime.
- As estatísticas indicam que os gols e o público possuem valores coerentes, sem números negativos.
- A base contém informações detalhadas, incluindo estatísticas ofensivas, defensivas, escanteios, faltas, chutes e dados dos elencos.
- A riqueza das variáveis permitirá realizar análises descritivas, comparações entre equipes e, futuramente, modelos preditivos.